import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBars,
  faSearch,
  faUser,
  faFileDownload,
  faFileUpload,
  faAngleUp,
  faAngleDown,
  faArrowUp,
  faArrowDown,
  faPlus,
  faSort,
  faBorderAll,
  faTimes,
  faArrowLeft,
  faArrowRight,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faBars,
  faSearch,
  faUser,
  faFileDownload,
  faFileUpload,
  faAngleUp,
  faAngleDown,
  faArrowUp,
  faArrowDown,
  faPlus,
  faSort,
  faBorderAll,
  faTimes,
  faArrowLeft,
  faArrowRight,
);
