module.exports = {
  ordering: {
    donors: [
      // width refers to column width
      // { key: '#', name: '#', width: '20px' },
      { key: 'id', name: 'Donor ID', width: '50px' },
      { key: 'salutation', name: 'Salutation', width: '50px' },
      { key: 'donorName', name: 'Donor Name', width: '70px' },
      { key: 'accountNumber', name: 'Account Number', width: '70px' },
      { key: 'accountName', name: 'Account Name', width: '70px' },
      { key: 'cellphoneNumber', name: 'Cellphone No.', width: '70px' },
      { key: 'emailAddress', name: 'Email', width: '100px' },
      { key: 'address1', name: 'Address 1', width: '100px' },
      { key: 'address2', name: 'Address 2', width: '100px' },
      { key: 'address3', name: 'Address 3', width: '100px' },
      { key: 'address4', name: 'Address 4', width: '100px' },
      { key: 'address5', name: 'Addres 5', width: '100px' },
      { key: 'birthDate', name: 'Birth Date', width: '100px' },
      { key: 'phone1', name: 'Phone 1', width: '100px' },
      { key: 'phone2', name: 'Phone 2', width: '100px' },
      { key: 'faxNumber', name: 'Fax No.', width: '100px' },
      { key: 'companyAddress', name: 'Company Address', width: '100px' },
      { key: 'companyTIN', name: 'Company TIN', width: '100px' },
      { key: 'createdBy', name: 'Created By', width: '100px' },
      { key: 'creationDate', name: 'Creation Date', width: '100px' },
      { key: 'lastModifiedBy', name: 'Last Modified By', width: '100px' },
      { key: 'lastModifiedDate', name: 'Last Modified Date', width: '100px' },
    ],
    donations: [
      // width refers to column width
      // { key: '#', name: '#', width: '20px' },
      { key: 'id', name: 'Donation ID', width: '50px' },
      { key: 'accountNumber', name: 'Account Number', width: '70px' },
      { key: 'accountName', name: 'Account Name', width: '60px' },
      { key: 'orNumber', name: 'OR Number', width: '70px' },
      { key: 'date', name: 'Date', width: '70px' },
      { key: 'amount', name: 'Amount', width: '70px' },
      { key: 'notes', name: 'Notes', width: '70px' },
      { key: 'orFiles', name: 'OR Files', width: '100px' },
      { key: 'tyFiles', name: 'TY Files', width: '100px' },
      { key: 'codFiles', name: 'COD Files', width: '100px' },
      { key: 'needCertificate', name: 'Need Certificate', width: '100px' },
      { key: 'purposeOfDonation', name: 'Purpose of Donation', width: '100px' },
    ],
  },
  tables: [
    'Donors',
    'Donations',
    'Scholars',
    'Scholarships',
    'MOAs',
    'Documents',
  ],
  dropdowns: {
    donors: [
      {
        key: 'id',
        name: 'Donor ID',
        routeAsc: 'donor/asc',
        routeDesc: 'donor/desc',
      },
      {
        key: 'donorName',
        name: 'Donor Name',
        routeAsc: 'donor/name/asc',
        routeDesc: 'donor/name/desc',
      },
      {
        key: 'accountName',
        name: 'Account Name',
        routeAsc: 'donor/account/asc',
        routeDesc: 'donor/account/desc',
      },
    ],
    donations: [
      {
        key: 'id',
        name: 'Donation ID',
        routeAsc: 'donation/asc',
        routeDesc: 'donation/desc',
      },
    ],
  },
  defaultTable: 'donors',
};
